package com.ethcad.ultimatearmory;

import net.minecraft.item.Item;
import net.minecraft.item.Item.ToolMaterial;
import net.minecraft.item.ItemArmor.ArmorMaterial;
import net.minecraftforge.common.util.EnumHelper;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.relauncher.Side;

import com.ethcad.ultimatearmory.items.AutoArrow;
import com.ethcad.ultimatearmory.items.Bomb;
import com.ethcad.ultimatearmory.items.ChainMail;
import com.ethcad.ultimatearmory.items.CrossBow;
import com.ethcad.ultimatearmory.items.DiamondBat;
import com.ethcad.ultimatearmory.items.GoldenBat;
import com.ethcad.ultimatearmory.items.GrenadeLauncher;
import com.ethcad.ultimatearmory.items.InstaBomb;
import com.ethcad.ultimatearmory.items.IronBat;
import com.ethcad.ultimatearmory.items.StoneBat;
import com.ethcad.ultimatearmory.items.TeleporterGun;
import com.ethcad.ultimatearmory.items.Wand;
import com.ethcad.ultimatearmory.items.WoodenBat;
import com.ethcad.ultimatearmory.items.adamantium.AdamantiumArmor;
import com.ethcad.ultimatearmory.items.adamantium.AdamantiumAxe;
import com.ethcad.ultimatearmory.items.adamantium.AdamantiumBat;
import com.ethcad.ultimatearmory.items.adamantium.AdamantiumClaws;
import com.ethcad.ultimatearmory.items.adamantium.AdamantiumHoe;
import com.ethcad.ultimatearmory.items.adamantium.AdamantiumIngot;
import com.ethcad.ultimatearmory.items.adamantium.AdamantiumPickaxe;
import com.ethcad.ultimatearmory.items.adamantium.AdamantiumSpade;
import com.ethcad.ultimatearmory.items.adamantium.AdamantiumSword;
import com.ethcad.ultimatearmory.items.emerald.EmeraldArmor;
import com.ethcad.ultimatearmory.items.emerald.EmeraldAxe;
import com.ethcad.ultimatearmory.items.emerald.EmeraldBat;
import com.ethcad.ultimatearmory.items.emerald.EmeraldHoe;
import com.ethcad.ultimatearmory.items.emerald.EmeraldPickaxe;
import com.ethcad.ultimatearmory.items.emerald.EmeraldSpade;
import com.ethcad.ultimatearmory.items.emerald.EmeraldSword;
import com.ethcad.ultimatearmory.items.obsidian.ObsidianArmor;
import com.ethcad.ultimatearmory.items.obsidian.ObsidianAxe;
import com.ethcad.ultimatearmory.items.obsidian.ObsidianBat;
import com.ethcad.ultimatearmory.items.obsidian.ObsidianHoe;
import com.ethcad.ultimatearmory.items.obsidian.ObsidianPickaxe;
import com.ethcad.ultimatearmory.items.obsidian.ObsidianSpade;
import com.ethcad.ultimatearmory.items.obsidian.ObsidianSword;
import com.ethcad.ultimatearmory.items.ruby.RubyArmor;
import com.ethcad.ultimatearmory.items.ruby.RubyAxe;
import com.ethcad.ultimatearmory.items.ruby.RubyBat;
import com.ethcad.ultimatearmory.items.ruby.RubyGem;
import com.ethcad.ultimatearmory.items.ruby.RubyHoe;
import com.ethcad.ultimatearmory.items.ruby.RubyPickaxe;
import com.ethcad.ultimatearmory.items.ruby.RubySpade;
import com.ethcad.ultimatearmory.items.ruby.RubySword;
import com.ethcad.ultimatearmory.items.vibranium.VibraniumArmor;
import com.ethcad.ultimatearmory.items.vibranium.VibraniumAxe;
import com.ethcad.ultimatearmory.items.vibranium.VibraniumBat;
import com.ethcad.ultimatearmory.items.vibranium.VibraniumDust;
import com.ethcad.ultimatearmory.items.vibranium.VibraniumHoe;
import com.ethcad.ultimatearmory.items.vibranium.VibraniumIngot;
import com.ethcad.ultimatearmory.items.vibranium.VibraniumPickaxe;
import com.ethcad.ultimatearmory.items.vibranium.VibraniumShield;
import com.ethcad.ultimatearmory.items.vibranium.VibraniumSpade;
import com.ethcad.ultimatearmory.items.vibranium.VibraniumSword;

public class ModItems {
	// Create ToolMaterial and ArmorMaterials
	public static ArmorMaterial armorEmerald = EnumHelper.addArmorMaterial("armorEmerald", "armorEmerald", 40, new int[] { 3, 5, 4, 3 }, 30);
	public static ToolMaterial legitEmerald = EnumHelper.addToolMaterial("legitEmerald", 3, 4096, 12.0f, 3.0f, 40);
	public static ToolMaterial adamantium = EnumHelper.addToolMaterial("adamantium", 2, 3072, 6f, 2f, 13);
	public static ArmorMaterial adamantiumArmorMaterial = EnumHelper.addArmorMaterial("adamantiumArmorMaterial", "adamantiumArmorMaterial", 40, new int[] { 3, 5, 4, 3 }, 30);
	public static ToolMaterial vibranium = EnumHelper.addToolMaterial("vibranium", 3, 2048, 8f, 4f, 10);
	public static ArmorMaterial armorVibranium = EnumHelper.addArmorMaterial("armorVibranium", "armorVibranium", 30, new int[] { 6, 7, 6, 5 }, 10);
	public static ToolMaterial obsidian = EnumHelper.addToolMaterial("obsidian", 4, 8192, 6f, 2f, 10);
	public static ArmorMaterial armorObsidian = EnumHelper.addArmorMaterial("armorObsidian", "armorObsidian", 200, new int[] { 4, 4, 4, 4 }, 10);
	public static ToolMaterial ruby = EnumHelper.addToolMaterial("ruby", 5, 10, 500f, 496f, 1);
	public static ArmorMaterial armorRuby = EnumHelper.addArmorMaterial("armorRuby", "armorRuby", 10, new int[] { 10, 10, 10, 10 }, 1);
	// Declare all the items
	public static Item emeraldPickaxe;
	public static Item emeraldHoe;
	public static Item emeraldSpade;
	public static Item emeraldAxe;
	public static Item emeraldSword;
	public static Item emeraldHelmet;
	public static Item emeraldChestplate;
	public static Item emeraldLeggings;
	public static Item emeraldBoots;
	public static Item obsidianPickaxe;
	public static Item obsidianHoe;
	public static Item obsidianSpade;
	public static Item obsidianAxe;
	public static Item obsidianSword;
	public static Item obsidianHelmet;
	public static Item obsidianChestplate;
	public static Item obsidianLeggings;
	public static Item obsidianBoots;
	public static Item obsidianBat;
	public static Item bomb;
	public static Item instaBomb;
	public static Item wand;
	public static Item adamantiumIngot;
	public static Item adamantiumClaws;
	public static Item adamantiumSword;
	public static Item adamantiumPickaxe;
	public static Item adamantiumSpade;
	public static Item adamantiumAxe;
	public static Item adamantiumHoe;
	public static Item adamantiumHelmet;
	public static Item adamantiumChestplate;
	public static Item adamantiumLeggings;
	public static Item adamantiumBoots;
	public static Item chainMail;
	public static Item vibraniumDust;
	public static Item woodenBat;
	public static Item stoneBat;
	public static Item ironBat;
	public static Item goldenBat;
	public static Item diamondBat;
	public static Item adamantiumBat;
	public static Item emeraldBat;
	public static Item vibraniumIngot;
	public static Item vibraniumShield;
	public static Item vibraniumSword;
	public static Item vibraniumPickaxe;
	public static Item vibraniumSpade;
	public static Item vibraniumAxe;
	public static Item vibraniumHoe;
	public static Item vibraniumHelmet;
	public static Item vibraniumChestplate;
	public static Item vibraniumLeggings;
	public static Item vibraniumBoots;
	public static Item vibraniumBat;
	public static Item grenadeLauncher;
	public static Item teleporterGun;
	public static Item rubyGem;
	public static Item rubySword;
	public static Item rubyPickaxe;
	public static Item rubySpade;
	public static Item rubyAxe;
	public static Item rubyHoe;
	public static Item rubyHelmet;
	public static Item rubyChestplate;
	public static Item rubyLeggings;
	public static Item rubyBoots;
	public static Item rubyBat;
	public static Item autoArrow;
	public static Item crossBow;
	
	// Initialize the items
	public static void loadItems() {
		adamantiumIngot = new AdamantiumIngot();
		adamantiumSword = new AdamantiumSword(adamantium);
		adamantiumPickaxe = new AdamantiumPickaxe(adamantium);
		adamantiumSpade = new AdamantiumSpade(adamantium);
		adamantiumAxe = new AdamantiumAxe(adamantium);
		adamantiumHoe = new AdamantiumHoe(adamantium);
		adamantiumClaws = new AdamantiumClaws(adamantium);
		woodenBat = new WoodenBat(ToolMaterial.WOOD);
		stoneBat = new StoneBat(ToolMaterial.STONE);
		ironBat = new IronBat(ToolMaterial.IRON);
		goldenBat = new GoldenBat(ToolMaterial.GOLD);
		diamondBat = new DiamondBat(ToolMaterial.EMERALD);
		adamantiumBat = new AdamantiumBat(adamantium);
		emeraldBat = new EmeraldBat(legitEmerald);
		chainMail = new ChainMail();
		adamantiumHelmet = new AdamantiumArmor(adamantiumArmorMaterial, 1, 0, "adamantiumHelmet");
		adamantiumChestplate = new AdamantiumArmor(adamantiumArmorMaterial, 1, 1, "adamantiumChestplate");
		adamantiumLeggings = new AdamantiumArmor(adamantiumArmorMaterial, 2, 2, "adamantiumLeggings");
		adamantiumBoots = new AdamantiumArmor(adamantiumArmorMaterial, 1, 3, "adamantiumBoots");
		emeraldPickaxe = new EmeraldPickaxe(legitEmerald);
		emeraldHoe = new EmeraldHoe(legitEmerald);
		emeraldSpade = new EmeraldSpade(legitEmerald);
		emeraldAxe = new EmeraldAxe(legitEmerald);
		emeraldSword = new EmeraldSword(legitEmerald);
		emeraldHelmet = new EmeraldArmor(armorEmerald, 1, 0, "emeraldHelmet");
		emeraldChestplate = new EmeraldArmor(armorEmerald, 1, 1, "emeraldChestplate");
		emeraldLeggings = new EmeraldArmor(armorEmerald, 2, 2, "emeraldLeggings");
		emeraldBoots = new EmeraldArmor(armorEmerald, 1, 3, "emeraldBoots");
		bomb = new Bomb();
		instaBomb = new InstaBomb();
		wand = new Wand();
		vibraniumIngot = new VibraniumIngot();
		vibraniumDust = new VibraniumDust();
		vibraniumSword = new VibraniumSword(vibranium);
		vibraniumPickaxe = new VibraniumPickaxe(vibranium);
		vibraniumSpade = new VibraniumSpade(vibranium);
		vibraniumAxe = new VibraniumAxe(vibranium);
		vibraniumHoe = new VibraniumHoe(vibranium);
		vibraniumShield = new VibraniumShield(vibranium);
		vibraniumBat = new VibraniumBat(vibranium);
		vibraniumHelmet = new VibraniumArmor(armorVibranium, 1, 0, "vibraniumHelmet");
		vibraniumChestplate = new VibraniumArmor(armorVibranium, 1, 1, "vibraniumChestplate");
		vibraniumLeggings = new VibraniumArmor(armorVibranium, 2, 2, "vibraniumLeggings");
		vibraniumBoots = new VibraniumArmor(armorVibranium, 1, 3, "vibraniumBoots");
		obsidianPickaxe = new ObsidianPickaxe(obsidian);
		obsidianHoe = new ObsidianHoe(obsidian);
		obsidianSpade = new ObsidianSpade(obsidian);
		obsidianAxe = new ObsidianAxe(obsidian);
		obsidianSword = new ObsidianSword(obsidian);
		obsidianBat = new ObsidianBat(obsidian);
		obsidianHelmet = new ObsidianArmor(armorObsidian, 1, 0, "obsidianHelmet");
		obsidianChestplate = new ObsidianArmor(armorObsidian, 1, 1, "obsidianChestplate");
		obsidianLeggings = new ObsidianArmor(armorObsidian, 2, 2, "obsidianLeggings");
		obsidianBoots = new ObsidianArmor(armorObsidian, 1, 3, "obsidianBoots");
		grenadeLauncher = new GrenadeLauncher();
		autoArrow = new AutoArrow();
		crossBow = new CrossBow();
		rubyGem = new RubyGem();
		rubySword = new RubySword(ruby);
		rubyPickaxe = new RubyPickaxe(ruby);
		rubySpade = new RubySpade(ruby);
		rubyAxe = new RubyAxe(ruby);
		rubyHoe = new RubyHoe(ruby);
		rubyBat = new RubyBat(ruby);
		rubyHelmet = new RubyArmor(armorRuby, 1, 0, "rubyHelmet");
		rubyChestplate = new RubyArmor(armorRuby, 1, 1, "rubyChestplate");
		rubyLeggings = new RubyArmor(armorRuby, 2, 2, "rubyLeggings");
		rubyBoots = new RubyArmor(armorRuby, 1, 3, "rubyBoots");
		teleporterGun = new TeleporterGun();
	}
}
